version: "3.7"

networks:
    laravel-app-network:

services:
    mysql:
        image: mariadb:10.4
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            -  "3307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel-app-network
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php81
        ports:
            - "9000:9000"
        volumes:
            -   ./src:/var/www/html
        networks:
            - laravel-app-network
    nginx:
        image: nginx:1.17-alpine
        container_name: nginx
        ports:
            - "8088:80"
            - "443:443"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel-app-network
